[build]
  publish = "dist/travel-weather"

  # Default build command.
  command = "npm run build"

  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200